name: Build & Deploy

on:
  push:            # trigger op elke push (alle branches)
    branches: ["**"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      TARGET_DIR: ${{ secrets.TARGET_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Detecteer build output (CRA=build, Vite=dist)
      - name: Detect output dir
        id: out
        run: |
          if [ -d "build" ]; then echo "dir=build" >> $GITHUB_OUTPUT; exit 0; fi
          if [ -d "dist" ]; then echo "dir=dist" >> $GITHUB_OUTPUT; exit 0; fi
          echo "Geen build output gevonden"; exit 1

      - name: Prepare SSH
        run: |
          install -m 700 -d ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # host key toevoegen (veiligere check dan StrictHostKeyChecking=no)
          ssh-keyscan -p "${SSH_PORT:-22}" "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Rsync deploy
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -p ${SSH_PORT:-22}" \
            "${{ steps.out.outputs.dir }}/" \
            "${SSH_USER}@${SSH_HOST}:${TARGET_DIR}"

      - name: Reload Apache (best effort)
        run: |
          ssh -i ~/.ssh/id_ed25519 -p "${SSH_PORT:-22}" \
            "${SSH_USER}@${SSH_HOST}" "sudo systemctl reload apache2 || true"